"""Export the fixed VGG-inspired CNN reference model used for comparison.

The convolutional geometry is deliberately explicit rather than randomly
sampled: 32-32-Pool-64-64-Pool-128.  It uses the same FlexibleCNN classifier
(AdaptiveAvgPool2d(1) followed by Linear(128, 10)) as the generated models.
"""

from __future__ import annotations

import argparse
import csv
from datetime import datetime, timezone
from pathlib import Path

import onnx

from FlexibleCNN import FlexibleCNN, ModelConfig, count_parameters
from generate_dataset import export_and_record


REFERENCE_NAME = "vgg_inspired_32_32_64_64_128"
CHANNELS = [32, 32, 64, 64, 128]
POOLS = [2, 4]
CLASSIFIER_DESCRIPTION = "AdaptiveAvgPool2d(1)_then_Linear(128,10)"

REFERENCE_FIELDS = [
    "id",
    "candidate_id",
    "reference_name",
    "architecture_family",
    "selection_reason",
    "seed",
    "depth",
    "pattern",
    "growth_pattern",
    "noise_ratio",
    "min_channels",
    "max_channels",
    "channels",
    "pools",
    "parameter_count",
    "classifier",
    "onnx_path",
    "onnx_size_bytes",
    "created_at_utc",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-id", type=int, default=551)
    parser.add_argument("--seed", type=int, default=20260918)
    parser.add_argument("--onnx-dir", type=Path, default=Path("model_onnx"))
    parser.add_argument("--dataset-structure-csv", type=Path, default=Path("dataset_structure.csv"))
    parser.add_argument(
        "--reference-csv",
        type=Path,
        default=Path("measurements/reference_models/reference_models.csv"),
    )
    return parser.parse_args()


def has_model_id(csv_path: Path, model_id: str) -> bool:
    if not csv_path.is_file() or csv_path.stat().st_size == 0:
        return False
    with csv_path.open("r", encoding="utf-8-sig", newline="") as file:
        return any(str(row.get("id", "")).zfill(4) == model_id for row in csv.DictReader(file))


def main() -> None:
    args = parse_args()
    if args.model_id <= 0:
        raise ValueError("--model-id must be positive.")
    id_text = f"{args.model_id:04d}"
    onnx_path = args.onnx_dir / f"{id_text}.onnx"
    if onnx_path.exists():
        raise FileExistsError(f"Refusing to overwrite existing model: {onnx_path}")
    if has_model_id(args.dataset_structure_csv, id_text):
        raise FileExistsError(f"Model ID {id_text} already exists in {args.dataset_structure_csv}")
    if args.reference_csv.exists():
        raise FileExistsError(f"Refusing to overwrite existing reference metadata: {args.reference_csv}")

    parameter_count = count_parameters(CHANNELS)
    config = ModelConfig(
        depth=len(CHANNELS),
        channels=CHANNELS,
        pools=POOLS,
        # This is an increasing channel sequence. The exact VGG-style steps
        # are recorded in the channels field rather than generated by a curve.
        pattern="increasing",
        growth_pattern="linear",
        noise_ratio=0.0,
        min_channels=min(CHANNELS),
        max_channels=max(CHANNELS),
        seed=args.seed,
        parameter_count=parameter_count,
    )
    exported_path = export_and_record(config, args.model_id, args.onnx_dir, args.dataset_structure_csv)
    onnx.checker.check_model(onnx.load(str(exported_path)))

    created_at = datetime.now(timezone.utc).isoformat()
    args.reference_csv.parent.mkdir(parents=True, exist_ok=True)
    record = {
        "id": id_text,
        "candidate_id": REFERENCE_NAME,
        "reference_name": REFERENCE_NAME,
        "architecture_family": "VGG-inspired",
        "selection_reason": "fixed_reference_baseline",
        "seed": config.seed,
        "depth": config.depth,
        "pattern": config.pattern,
        "growth_pattern": config.growth_pattern,
        "noise_ratio": config.noise_ratio,
        "min_channels": config.min_channels,
        "max_channels": config.max_channels,
        "channels": "-".join(map(str, config.channels)),
        "pools": "-".join(map(str, config.pools)),
        "parameter_count": config.parameter_count,
        "classifier": CLASSIFIER_DESCRIPTION,
        "onnx_path": exported_path.as_posix(),
        "onnx_size_bytes": exported_path.stat().st_size,
        "created_at_utc": created_at,
    }
    with args.reference_csv.open("w", encoding="utf-8-sig", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=REFERENCE_FIELDS)
        writer.writeheader()
        writer.writerow(record)

    print(f"Exported reference model {id_text}: {REFERENCE_NAME}")
    print(f"  Channels: {record['channels']} | Pools after blocks: {record['pools']}")
    print(f"  Parameters: {config.parameter_count:,} | Classifier: {CLASSIFIER_DESCRIPTION}")
    print(f"  ONNX validated: {exported_path}")
    print(f"  Reference metadata: {args.reference_csv}")


if __name__ == "__main__":
    main()
